[tool.robotpy]
robot_class = "MyRobot"  # <-- Replace this with your actual robot class name
robotpy_version = "2025.2.1.2"

[build-system]
requires = ["robotpy", "robotpy-rev", "robotpy-wpilib", "setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"
